### ISSUE TITLE
如何调用echarts实例化的方法

### ISSUE THREAD

**Issue by yunhailu** [panteng/vue-echarts#4]
当我利用指令传递参数 v-echarts="option" 时，像echarts一些实例化的方法怎么可以调用呢？

Example：
    var myChart = echarts.init(document.getElementById('main'));
    myChart.setOption(option);
    myChart.on('click', function (params) {
        // do something
    });
    myChart.resize();

这个例子是普通echarts的调用，但是类似on的监听，自定义的resize调用，利用v-echarts该如何做呢？

**Comment by panteng** [comment]
刚刚更新了文档，里面有讲到如何访问Echarts实例。https://github.com/panteng/vue-echarts/blob/master/README.md
