### ISSUE TITLE
vue升级2.0 如果有空余时间麻烦作者也做个升级 谢谢啦

### ISSUE THREAD

**Issue by 419921017** [panteng/vue-echarts#6]
vue升级2.0 如果有空余时间麻烦作者也做个升级 谢谢啦

**Comment by panteng** [comment]
感谢建议，不过目前没有精力去升级。

**Comment by panteng** [comment]
https://github.com/panteng/vue-echarts/releases/tag/v0.2.0
Vue.js 2 support added.
